### ISSUE TITLE
[Bug]: Centos 7 with Java 

### ISSUE THREAD

**Issue by bluenor** [dgibbs64/linuxgsm#4133]
### User story

I would like to launch Zomboid Project

### Game

Zomboid Project

### Linux distro

CentOS

### Command

command: start

### Further information

First of all, I wanted to congratulate the staff on a job well done. And I also wanted to report a problem that I have been experiencing not only using linuxgsm but on my server in general, I thought that you who are more experienced than me could help me understand how to solve it.

### Relevant log output

```shell
cat 06-03-23_07-48-49_DebugLog-server.txt
[06-03-23 07:48:49.289] LOG  : General     , 1678085329288> 3,051,654,711> cachedir set to "/home/pzserver/Zomboid".
[06-03-23 07:48:49.303] ERROR: General     , 1678085329303> 3,051,654,726> java.lang.UnsatisfiedLinkError: /home/pzserver/serverfiles/natives/libPZClipper64.so: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/pzserver/serverfiles/natives/libPZClipper64.so).
[06-03-23 07:48:49.304] ERROR: General     , 1678085329303> 3,051,654,726>      at java.base/jdk.internal.loader.NativeLibraries.load(Native Method).
[06-03-23 07:48:49.304] ERROR: General     , 1678085329304> 3,051,654,726>      at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source).
[06-03-23 07:48:49.304] ERROR: General     , 1678085329304> 3,051,654,727>      at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source).
[06-03-23 07:48:49.305] ERROR: General     , 1678085329304> 3,051,654,727>      at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source).
[06-03-23 07:48:49.305] ERROR: General     , 1678085329305> 3,051,654,727>      at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(Unknown Source).
[06-03-23 07:48:49.305] ERROR: General     , 1678085329305> 3,051,654,728>      at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source).
[06-03-23 07:48:49.305] ERROR: General     , 1678085329305> 3,051,654,728>      at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source).
[06-03-23 07:48:49.306] ERROR: General     , 1678085329306> 3,051,654,728>      at java.base/java.lang.Runtime.loadLibrary0(Unknown Source).
[06-03-23 07:48:49.306] ERROR: General     , 1678085329306> 3,051,654,729>      at java.base/java.lang.System.loadLibrary(Unknown Source).
[06-03-23 07:48:49.306] ERROR: General     , 1678085329306> 3,051,654,729>      at zombie.vehicles.Clipper.init(Clipper.java:24).
[06-03-23 07:48:49.306] ERROR: General     , 1678085329306> 3,051,654,729>      at zombie.network.GameServer.main(GameServer.java:329).
```

### Steps to reproduce

When i go in debug mode, i see this. Anyway it's not a problem of linuxgsm i have this problem even if i make the standard steamcmd installation and start. Anyone know how i could solve it?

**Comment by dgibbs64** [comment]
My only recommendation would be to upgrade to Rocky/Alma 8 or 9 at this point. CentOS 7 is extremely old now.
