### ISSUE TITLE
[gsquery] TypeError

### ISSUE THREAD

**Issue by m-rousse** [dgibbs64/linuxgsm#964]
After a fresh installation of a TeamFortress2 server, I was not able to monitor it :

```sh
[testlgsm@myserver:~/TF2]$ ./tf2server start
[  OK  ] Starting tf2-server: Test Server LGSM
[testlgsm@myserver:~/TF2]$ ./tf2server monitor
[  OK  ] Monitor tf2-server: Checking session: OK
[ FAIL ] Monitor tf2-server: Querying port: 10.240.0.1:27015 : 0/1 : Traceback (most recent call last):
  File "/home/testlgsm/TF2/lgsm/functions/gsquery.py", line 125, in <module>
    server.responding()
  File "/home/testlgsm/TF2/lgsm/functions/gsquery.py", line 61, in responding
    connection.send( self.query_prompt_string )
...
[ FAIL ] Monitor tf2-server: Querying port: 10.240.0.1:27015 : 3/1 : Traceback (most recent call last):
  File "/home/testlgsm/TF2/lgsm/functions/gsquery.py", line 125, in <module>
    server.responding()
  File "/home/testlgsm/TF2/lgsm/functions/gsquery.py", line 61, in responding
    connection.send( self.query_prompt_string )
```
I patched it by adding a b in front of the query strings in gsquery.py :
```python
       self.query_prompt_string = b'\xFF\xFF\xFF\xFFTSource Engine Query\0'
elif self.option.engine == 'goldsource':
       self.query_prompt_string = b'\xFF\xFF\xFF\xFFTSource Engine Query\0'
       ...
elif self.option.engine == 'avalanche':
       self.query_prompt_string = b'\xFE\xFD\x09\x10\x20\x30\x40'
```
I am using python 3.5.2.
Is it really an issue, should I send a Pull-Request of this small fix ?

Best regards, Mathieu

**Comment by UltimateByte** [comment]
Hey,

Well, this function has been developped for python 2.x.
The only question is : Would this change break compatibility with older versions ?

**Comment by UltimateByte** [comment]
`Python version (currently v2.7).`
Your fix works with it.
Don't bother, i'll pull request the change. :)

**Comment by m-rousse** [comment]
Perfect, thank you :)
